# Generated by Django 4.2.7 on 2023-11-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomusuario', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('contra', models.CharField(max_length=200)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('total_publicaciones', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('total_publicaciones', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
