# Generated by Django 4.2.7 on 2023-11-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_delete_perfil2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='loginid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
