# Generated by Django 4.2.7 on 2023-11-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_usuario_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='loginid',
        ),
    ]
