# Generated by Django 4.2.7 on 2023-11-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
