# Generated by Django 4.2.7 on 2023-11-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_alter_usuario_contra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contra',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='valor_por_defecto', max_length=200, null=True),
        ),
    ]
