# Generated by Django 4.2.7 on 2023-11-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_remove_usuario_last_login_remove_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contra',
            field=models.CharField(max_length=200),
        ),
    ]
