# Generated by Django 4.2.7 on 2023-11-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0010_alter_usuario_contra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
