# Generated by Django 4.2.7 on 2023-11-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0011_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nomusuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
