# Generated by Django 4.2.7 on 2023-11-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0017_alter_usuarios_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contra',
        ),
    ]
