# Generated by Django 4.2.7 on 2023-11-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0020_alter_usuarios_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='celular',
            field=models.IntegerField(),
        ),
    ]
