# Generated by Django 4.2.7 on 2023-12-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0026_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nomuser',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
