# Generated by Django 4.2.7 on 2023-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0027_usuario_nomuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nomuser',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
