# Generated by Django 4.2.7 on 2023-12-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0028_alter_usuario_nomuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nomuser',
        ),
    ]
