# Generated by Django 4.2.7 on 2023-11-16 21:25

import Apps.ReconocimientosDPrecio.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImagenDprenda', models.ImageField(blank=True, null=True, upload_to=Apps.ReconocimientosDPrecio.utils.imgPrenda_media_path)),
            ],
        ),
    ]
