# Generated by Django 4.2.7 on 2023-11-16 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0025_alter_perfil_imagen'),
        ('ReconocimientosDPrecio', '0002_imagenes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='Usuario.perfil'),
        ),
    ]
