# Generated by Django 4.2.7 on 2023-11-18 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0026_alter_perfil_usuario'),
        ('ReconocimientosDPrecio', '0004_detalleia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleia',
            name='imagen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReconocimientosDPrecio.imagenes'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Usuario.perfil'),
        ),
    ]
