# Generated by Django 4.2.7 on 2023-11-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0026_alter_perfil_usuario'),
        ('ReconocimientosDPrecio', '0006_alter_imagenes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.perfil'),
        ),
    ]
