# Generated by Django 4.2.7 on 2023-12-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReconocimientosDPrecio', '0007_alter_imagenes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleia',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
