# Generated by Django 4.2.7 on 2023-11-18 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReconocimientosDPrecio', '0005_alter_detalleia_imagen_alter_imagenes_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('DetalleIA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ReconocimientosDPrecio.detalleia')),
            ],
        ),
    ]
